import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import AppProvider from '@/components/provider/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <AppProvider>
          <Header />
          <main className="min-h-[92vh] h-full">{children}</main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
